### ISSUE TITLE
Update for Zig 0.8.0

### ISSUE THREAD

**Issue by holobeat** [FireFox317/avr-arduino-zig#2]
`zig build` won't compile due to update in 0.8.0 release:

> @import("builtin") no longer re-exports std.builtin

StackTrace struct is now accessed via `@import("std").builtin.StackTrace`

Updating start.zig panic function to:
`error_return_trace: ?*@import("std").builtin.StackTrace` solves the issue.

**Comment by kassane** [comment]
Done! #4
